"""Where uploaded vetting documents live.

These are photo IDs and insurance certificates. Two rules follow from that and
are enforced here rather than left to each caller:

* **Nothing is ever served from a public path.** Files are written under a
  directory the web server does not expose, and the only way back out is an
  authenticated endpoint that checks who is asking. A "just link to it" upload
  directory is how a government ID ends up indexed.
* **The key is generated, never taken from the client.** An attacker-supplied
  filename is a path-traversal primitive; the original name is kept as a plain
  column for the admin to read, not as a path.

The backend is an interface with one implementation because the pilot runs a
single container. Object storage (S3, R2) slots in behind the same three
methods when there is more than one, and the `LocalDiskStorage` docstring says
what that means for Railway.
"""

from __future__ import annotations

import os
import secrets
import uuid
from abc import ABC, abstractmethod
from pathlib import Path
from typing import BinaryIO

from app.config import settings

#: What a vetting document is allowed to be. A photo or a PDF, nothing else —
#: an upload field that accepts anything is an upload field that accepts HTML.
ALLOWED_CONTENT_TYPES: dict[str, str] = {
    "image/jpeg": ".jpg",
    "image/png": ".png",
    "image/heic": ".heic",
    "image/webp": ".webp",
    "application/pdf": ".pdf",
}


class DocumentTooLarge(Exception):
    """Raised when an upload exceeds the configured size limit."""


class UnsupportedDocumentType(Exception):
    """Raised for a content type outside ALLOWED_CONTENT_TYPES."""


class DocumentStorage(ABC):
    @abstractmethod
    def save(self, *, stream: BinaryIO, content_type: str, cleaner_id: uuid.UUID) -> str:
        """Store the stream and return the storage key to persist."""

    @abstractmethod
    def open(self, key: str) -> BinaryIO:
        """Open a stored document for reading."""

    @abstractmethod
    def delete(self, key: str) -> None:
        """Remove a stored document. Missing keys are not an error."""


class LocalDiskStorage(DocumentStorage):
    """Writes to a directory on local disk.

    **On Railway this directory must be a mounted volume.** A container's
    filesystem is replaced on every deploy, so without one the IDs a cleaner
    uploaded vanish at the next push and the admin queue points at files that
    are no longer there — silently, because the rows survive.
    """

    def __init__(self, root: str | Path | None = None) -> None:
        self.root = Path(root or settings.document_storage_dir)

    def _path_for(self, key: str) -> Path:
        # Keys are generated by `save`, but this is the one place a key becomes
        # a filesystem path, so it is also where a crafted key gets stopped.
        candidate = (self.root / key).resolve()
        root = self.root.resolve()
        if not candidate.is_relative_to(root):
            raise ValueError(f"storage key escapes the storage root: {key!r}")
        return candidate

    def save(self, *, stream: BinaryIO, content_type: str, cleaner_id: uuid.UUID) -> str:
        extension = ALLOWED_CONTENT_TYPES.get(content_type)
        if extension is None:
            raise UnsupportedDocumentType(content_type)

        # Per-cleaner folder, random filename. The name carries no guessable
        # information and no client-supplied text.
        key = f"{cleaner_id}/{secrets.token_urlsafe(24)}{extension}"
        destination = self._path_for(key)
        destination.parent.mkdir(parents=True, exist_ok=True)

        limit = settings.max_document_bytes
        written = 0
        # Streamed in chunks and aborted on overrun, so an oversized upload
        # cannot fill the disk before the size is known. Content-Length is
        # client-supplied and not a limit.
        try:
            with open(destination, "wb") as handle:
                while chunk := stream.read(64 * 1024):
                    written += len(chunk)
                    if written > limit:
                        raise DocumentTooLarge(
                            f"document exceeds the {limit} byte limit"
                        )
                    handle.write(chunk)
        except BaseException:
            destination.unlink(missing_ok=True)
            raise

        if written == 0:
            destination.unlink(missing_ok=True)
            raise UnsupportedDocumentType("the uploaded file was empty")

        os.chmod(destination, 0o600)
        return key

    def open(self, key: str) -> BinaryIO:
        return open(self._path_for(key), "rb")

    def delete(self, key: str) -> None:
        self._path_for(key).unlink(missing_ok=True)


def get_storage() -> DocumentStorage:
    """FastAPI dependency. One implementation today; the seam is the point."""
    return LocalDiskStorage()
