"""Bid → award → the gate code → backing out, clicked through in a browser.

The carry-over list asks for "a real click-through of bid → award → payment,
not just 'the button renders'". Payment is phase 6; this is the rest of it, and
the parts that only a browser can check are the handovers:

* the owner accepts a bid and the same screen has to turn into a booking — the
  accept answers with the turnover's detail shape, and a screen that replaced
  its state with anything smaller would go blank right after the click, which is
  exactly the bug that shipped here once before;
* the gate code has to *appear* on the cleaner's screen once they are hired,
  having been absent from every screen they saw while they were only bidding;
* and when they back out, the job has to be visibly back on the bench.
"""

from __future__ import annotations

import re
import uuid

import pytest

playwright_api = pytest.importorskip("playwright.sync_api")
expect = playwright_api.expect

pytestmark = pytest.mark.e2e


def _set_service_area(page) -> None:
    """Pick a town the way a cleaner does now.

    The form used to ask for latitude and longitude. It asks for a town, so
    these tests type one — which is the point of a browser test: the selector
    changing is the screen changing, and a test that still filled two hidden
    coordinate fields would pass against a form nobody can complete.
    """
    page.fill("#service-area-search", "Portland")
    page.get_by_test_id("place-portland").click()
    expect(page.get_by_test_id("service-area-chosen")).to_be_visible()

PASSWORD = "correct-horse-battery"
LOCKBOX_CODE = "4417"


def _signup(page, base_url: str, role: str, name: str) -> str:
    email = f"{role}-{uuid.uuid4().hex[:10]}@example.com"
    page.goto(f"{base_url}/signup?role={role}")
    page.fill("#full_name", name)
    page.fill("#email", email)
    page.fill("#password", PASSWORD)
    page.click("button[type=submit]")
    page.wait_for_url("**/dashboard")
    return email


def _clear_for_work(db, email: str) -> None:
    """Finish this cleaner's vetting the way an admin would.

    The click-through of vetting itself is `test_cleaner_flow.py`; repeating it
    here would make this test about the wrong thing. What it cannot do is write
    `can_take_jobs` — that column is generated by Postgres — so the statuses go
    through the same door the admin's buttons use.
    """
    from sqlalchemy import select

    from app.models import CleanerProfile, User, VerificationStatus

    user = db.execute(select(User).where(User.email == email)).scalar_one()
    profile = db.execute(
        select(CleanerProfile).where(CleanerProfile.user_id == user.id)
    ).scalar_one()
    profile.id_verification_status = VerificationStatus.APPROVED
    profile.background_check_status = VerificationStatus.APPROVED
    db.commit()


def _place_coordinates(db) -> None:
    from sqlalchemy import select

    from app.models import Property

    prop = db.execute(select(Property)).scalars().first()
    prop.lat, prop.lng = 43.6591, -70.2568
    db.commit()


def test_an_owner_hires_a_cleaner_and_the_cleaner_backs_out(
    make_page, live_server, db
) -> None:
    base_url = live_server
    owner_page, cleaner_page = make_page(), make_page()

    # --- the owner posts a job ---
    page = owner_page
    _signup(page, base_url, "owner", "Property Owner")

    page.goto(f"{base_url}/properties/new")
    page.fill("#nickname", "Seaside Cottage")
    page.fill("#address_line1", "1 Harbor Way")
    page.fill("#city", "Portland")
    page.fill("#state", "ME")
    page.fill("#postal_code", "04101")
    page.fill("#access_notes", f"Lockbox on the rail, code {LOCKBOX_CODE}.")
    page.click("button[type=submit]")
    page.wait_for_url(re.compile(r"/properties/[0-9a-fA-F-]{36}$"))
    _place_coordinates(db)

    page.goto(f"{base_url}/turnovers/new")
    page.fill("#checkout_at", "2027-05-20T11:00")
    page.fill("#checkin_at", "2027-05-20T16:00")
    page.fill("#budget", "145")
    page.click("button[type=submit]")
    page.wait_for_url(re.compile(r"/turnovers/[0-9a-fA-F-]{36}$"))
    turnover_url = page.url
    expect(page.get_by_text("No bids yet")).to_be_visible()

    # --- a cleared cleaner bids ---
    page = cleaner_page
    page.expected_errors.append("404 (Not Found)")  # first visit, no profile yet
    cleaner_email = _signup(page, base_url, "cleaner", "Dana Rivers")

    page.goto(f"{base_url}/cleaner/profile")
    _set_service_area(page)
    page.click("button[type=submit]")
    expect(page.get_by_role("heading", name="Not cleared to bid yet")).to_be_visible()

    _clear_for_work(db, cleaner_email)

    page.goto(f"{base_url}/board")
    expect(page.get_by_role("button", name="Place bid")).to_be_visible()
    page.fill("input[id^=price-]", "135")
    page.get_by_role("button", name="Place bid").click()
    expect(page.get_by_text(re.compile(r"Your bid:\s*\$135"))).to_be_visible()

    # Nothing they need to open a door — they have bid, not been hired.
    assert LOCKBOX_CODE not in page.inner_text("body")
    expect(page.get_by_role("link", name="Your jobs")).to_be_visible()
    page.get_by_role("link", name="Your jobs").click()
    page.wait_for_url("**/jobs")
    expect(page.get_by_text("No jobs booked yet")).to_be_visible()

    # --- the owner accepts ---
    page = owner_page
    page.goto(turnover_url)
    expect(page.get_by_test_id("bid")).to_have_count(1)
    expect(page.get_by_test_id("bid-price")).to_have_text("$135")
    expect(page.get_by_test_id("bid-status")).to_have_text("submitted")

    page.get_by_test_id("accept-bid").click()

    # The screen has to become a booking, not go blank.
    expect(page.get_by_test_id("award-panel")).to_be_visible()
    expect(page.get_by_test_id("award-cleaner")).to_have_text("Dana Rivers")
    expect(page.get_by_test_id("award-price")).to_have_text("$135")
    expect(page.get_by_test_id("status-badge")).to_have_text("Awarded")
    # The property is still on the page — the proof the action answered with
    # the full detail shape rather than something smaller.
    expect(page.get_by_role("heading", name="Seaside Cottage")).to_be_visible()

    # --- the cleaner now gets the address and the code ---
    page = cleaner_page
    page.goto(f"{base_url}/jobs")
    expect(page.get_by_test_id("job")).to_have_count(1)
    expect(page.get_by_test_id("job-address")).to_contain_text("1 Harbor Way")
    expect(page.get_by_test_id("job-access-notes")).to_contain_text(LOCKBOX_CODE)
    expect(page.get_by_test_id("job-price")).to_have_text("$135")

    # --- and backs out ---
    page.get_by_test_id("cancel-job").click()
    page.fill("textarea[id^=why-]", "My van is off the road.")
    page.get_by_test_id("confirm-cancel-job").click()

    # **The card stays, marked cancelled — and the gate code does not.**
    # It used to drop off the list entirely, and the assertion here was that
    # the screen was empty. That was a true description of a screen with a
    # problem: a cleaner's cancelled bookings were unreachable from the site,
    # and with them the dispute panel on the card, which is the only way a
    # cleaner can complain about a job that went wrong.
    #
    # The half of this that was always load-bearing is the second assertion.
    # Access follows the *live* award, decided once in `_serialize_job`, so
    # showing the card must not show the code — and this is what says so.
    expect(page.get_by_test_id("job")).to_have_count(1)
    expect(page.get_by_test_id("job")).to_contain_text("Cancelled")
    assert LOCKBOX_CODE not in page.inner_text("body"), (
        "the gate code outlived the booking"
    )

    # --- the owner sees it back on the bench ---
    page = owner_page
    page.goto(turnover_url)
    expect(page.get_by_test_id("status-badge")).to_have_text("Taking bids")
    expect(page.get_by_test_id("award-panel")).to_have_count(0)
    expect(page.get_by_test_id("bid-status")).to_have_text("withdrawn")

    # And somebody else can pick it up.
    other_page = make_page()
    other_page.expected_errors.append("404 (Not Found)")
    other_email = _signup(other_page, base_url, "cleaner", "Sam Okafor")
    other_page.goto(f"{base_url}/cleaner/profile")
    _set_service_area(other_page)
    other_page.click("button[type=submit]")
    # Wait for the save to land before reading the profile out of the database.
    # Without this the read races the request and finds no row — which is how
    # this test failed the first time it ran alongside the others.
    expect(
        other_page.get_by_role("heading", name="Not cleared to bid yet")
    ).to_be_visible()
    _clear_for_work(db, other_email)

    other_page.goto(f"{base_url}/board")
    expect(other_page.get_by_role("heading", name="Seaside Cottage")).to_be_visible()
    expect(other_page.get_by_role("button", name="Place bid")).to_be_visible()
